-- ==============================================
-- V3: create users table and link tenants to users
-- ==============================================

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sub VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    picture VARCHAR(1000),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP NULL
);

ALTER TABLE tenants ADD COLUMN user_id BIGINT NULL;

ALTER TABLE tenants
ADD CONSTRAINT fk_tenants_user FOREIGN KEY (user_id) REFERENCES users (id);